package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.ApppartnerTerminalEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.ApppartnerTerminalEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApppartnerTerminalEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    long countByExample(ApppartnerTerminalEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int deleteByExample(ApppartnerTerminalEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("terminalid") String terminalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int insert(ApppartnerTerminalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int insertSelective(ApppartnerTerminalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    List<ApppartnerTerminalEntity> selectByExample(ApppartnerTerminalEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    ApppartnerTerminalEntity selectByPrimaryKey(@Param("userId") String userId, @Param("terminalid") String terminalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApppartnerTerminalEntity record, @Param("example") ApppartnerTerminalEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApppartnerTerminalEntity record, @Param("example") ApppartnerTerminalEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApppartnerTerminalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartnerterminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApppartnerTerminalEntity record);
}