package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.AppPartnerEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.AppPartnerEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPartnerEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    long countByExample(AppPartnerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int deleteByExample(AppPartnerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int insert(AppPartnerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int insertSelective(AppPartnerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    List<AppPartnerEntity> selectByExample(AppPartnerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    AppPartnerEntity selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppPartnerEntity record, @Param("example") AppPartnerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppPartnerEntity record, @Param("example") AppPartnerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppPartnerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apppartner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppPartnerEntity record);
}