package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.BoxEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.BoxEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoxEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    long countByExample(BoxEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int deleteByExample(BoxEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("terminalid") String terminalid, @Param("boxid") Integer boxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int insert(BoxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int insertSelective(BoxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    List<BoxEntity> selectByExample(BoxEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    BoxEntity selectByPrimaryKey(@Param("terminalid") String terminalid, @Param("boxid") Integer boxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BoxEntity record, @Param("example") BoxEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BoxEntity record, @Param("example") BoxEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BoxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BoxEntity record);
}