package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.BusinessModelEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.BusinessModelEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface BusinessModelEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    long countByExample(BusinessModelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int deleteByExample(BusinessModelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("businesscode") Integer businesscode, @Param("configname") String configname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int insert(BusinessModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int insertSelective(BusinessModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    List<BusinessModelEntity> selectByExample(BusinessModelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    BusinessModelEntity selectByPrimaryKey(@Param("businesscode") Integer businesscode, @Param("configname") String configname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BusinessModelEntity record, @Param("example") BusinessModelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BusinessModelEntity record, @Param("example") BusinessModelEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businessmodel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessModelEntity record);
    
    @Select("select MAX(businesscode) as businessCode from businessmodel")
	BusinessModelEntity getLastInsert();
    
    @Select("select * from businessmodel where businesscode=#{code}")
    List<BusinessModelEntity> selectByKey(@Param("code")Integer code);
    
    /**
     * @param terminalid
     * @return
     * 身份验证
     */
    @Select("SELECT * from businessmodel where configname='ValidateIdentities' and +"
     +"businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel where +"
     +"terminal.businessCode=businessmodel.businessCode and terminal.terminalID=#{terminalid})")
	BusinessModelEntity selectByTerminaid(@Param("terminalid")String terminalid);
    
    @Select("SELECT configvalue from businessmodel where configname='TimeBetween' and businesscode=(SELECT Distinct b.businessCode from terminal t,businessmodel b"
     +" where t.businessCode=b.businessCode and  t.terminalid=#{terminalid})")
	BusinessModelEntity selectByIntervalTiem(@Param("terminalid")String terminalid);//存物间隔时间验证
    
    /**
     * @param terminalid
     * @return
     * 一卡一箱 
     */
    @Select("SELECT * from businessmodel where configname='OneCardOneBox' and +"
    	     +"businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel where +"
    	     +"terminal.businessCode=businessmodel.businessCode and terminal.terminalID=#{terminalid})")
	BusinessModelEntity selectByTerminaidk(String terminalid);
    
    /**
     * @param terminalid
     * @return
     * 惩罚标识
     */
    @Select("SELECT * from businessmodel where configname='LimitSwitch' and +"
    	     +"businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel where +"
    	     +"terminal.businessCode=businessmodel.businessCode and terminal.terminalID=#{terminalid})")
	BusinessModelEntity selectByTerminaidc(String terminalid);
    
    /**
     * @param terminalid
     * @return
     * 转换规则
     */
    @Select("SELECT * from businessmodel where configname='Rule' and +"
    	     +"businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel where +"
    	     +"terminal.businessCode=businessmodel.businessCode and terminal.terminalID=#{terminalid})")
	BusinessModelEntity selectByTerminaidz(String terminalid);
   
    /**
     * @param terminalid
     * @return
     * 收费功能
     */
    @Select("SELECT * from businessmodel where configname='ChargeFuncSwitch' and +"
   	     +"businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel where +"
   	     +"terminal.businessCode=businessmodel.businessCode and terminal.terminalID=#{terminalid})")
	BusinessModelEntity selectByTerminaidf(String terminalid);
//    /**
//     * @param terminalid
//     * @return
//     * 收费模式
//     */ 
//    @Select("SELECT * from businessmodel where configname='ChargeMode' and +"
//      	     +"businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel where +"
//      	     +"terminal.businessCode=businessmodel.businessCode and terminal.terminalID=#{terminalid})")
//	BusinessModelEntity selectByTerminaidm(String terminalid);
    
}