package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.CardAndBoxBoundEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.CardAndBoxBoundEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardAndBoxBoundEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    long countByExample(CardAndBoxBoundEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int deleteByExample(CardAndBoxBoundEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int insert(CardAndBoxBoundEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int insertSelective(CardAndBoxBoundEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    List<CardAndBoxBoundEntity> selectByExample(CardAndBoxBoundEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    CardAndBoxBoundEntity selectByPrimaryKey(String cardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CardAndBoxBoundEntity record, @Param("example") CardAndBoxBoundEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CardAndBoxBoundEntity record, @Param("example") CardAndBoxBoundEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CardAndBoxBoundEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardandboxbound
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CardAndBoxBoundEntity record);
}