package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.DictEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.DictEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    long countByExample(DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int deleteByExample(DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("dicttypecode") String dicttypecode, @Param("dictcode") Integer dictcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int insert(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int insertSelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    List<DictEntity> selectByExample(DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    DictEntity selectByPrimaryKey(@Param("dicttypecode") String dicttypecode, @Param("dictcode") Integer dictcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictEntity record, @Param("example") DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictEntity record, @Param("example") DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictEntity record);
}