package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.ManagerCheckInRecordEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.ManagerCheckInRecordEntityExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerCheckInRecordEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    long countByExample(ManagerCheckInRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int deleteByExample(ManagerCheckInRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("areacode") String areacode, @Param("managercardid") String managercardid, @Param("logindate") Date logindate, @Param("terminalid") String terminalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int insert(ManagerCheckInRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int insertSelective(ManagerCheckInRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    List<ManagerCheckInRecordEntity> selectByExample(ManagerCheckInRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    ManagerCheckInRecordEntity selectByPrimaryKey(@Param("areacode") String areacode, @Param("managercardid") String managercardid, @Param("logindate") Date logindate, @Param("terminalid") String terminalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManagerCheckInRecordEntity record, @Param("example") ManagerCheckInRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManagerCheckInRecordEntity record, @Param("example") ManagerCheckInRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManagerCheckInRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table managercheckinrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManagerCheckInRecordEntity record);
}