package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.MenuRightsEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.MenuRightsEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuRightsEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    long countByExample(MenuRightsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int deleteByExample(MenuRightsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("menucode") String menucode, @Param("rolecode") Integer rolecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int insert(MenuRightsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int insertSelective(MenuRightsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    List<MenuRightsEntity> selectByExample(MenuRightsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    MenuRightsEntity selectByPrimaryKey(@Param("menucode") String menucode, @Param("rolecode") Integer rolecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenuRightsEntity record, @Param("example") MenuRightsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenuRightsEntity record, @Param("example") MenuRightsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuRightsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menurights
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuRightsEntity record);
}