package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.MessageNoticeRecordEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.MessageNoticeRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageNoticeRecordEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    long countByExample(MessageNoticeRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int deleteByExample(MessageNoticeRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer waterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int insert(MessageNoticeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int insertSelective(MessageNoticeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    List<MessageNoticeRecordEntity> selectByExample(MessageNoticeRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    MessageNoticeRecordEntity selectByPrimaryKey(Integer waterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MessageNoticeRecordEntity record, @Param("example") MessageNoticeRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MessageNoticeRecordEntity record, @Param("example") MessageNoticeRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageNoticeRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagenoticerecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageNoticeRecordEntity record);
}