package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.OperatorDiaryEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.OperatorDiaryEntityExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperatorDiaryEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    long countByExample(OperatorDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("accountcode") String accountcode, @Param("date") Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int insert(OperatorDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int insertSelective(OperatorDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    List<OperatorDiaryEntity> selectByExample(OperatorDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    OperatorDiaryEntity selectByPrimaryKey(@Param("accountcode") String accountcode, @Param("date") Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorDiaryEntity record, @Param("example") OperatorDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorDiaryEntity record, @Param("example") OperatorDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatordiary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorDiaryEntity record);
}