package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.PaymentDetailEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.PaymentDetailEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentDetailEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    long countByExample(PaymentDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("masterid") Integer masterid, @Param("detailid") String detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int insert(PaymentDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int insertSelective(PaymentDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    List<PaymentDetailEntity> selectByExample(PaymentDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    PaymentDetailEntity selectByPrimaryKey(@Param("masterid") Integer masterid, @Param("detailid") String detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaymentDetailEntity record, @Param("example") PaymentDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaymentDetailEntity record, @Param("example") PaymentDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentDetailEntity record);
}