package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.PaymentMasterEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.PaymentMasterEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMasterEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    long countByExample(PaymentMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer masterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int insert(PaymentMasterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int insertSelective(PaymentMasterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    List<PaymentMasterEntity> selectByExample(PaymentMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    PaymentMasterEntity selectByPrimaryKey(Integer masterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaymentMasterEntity record, @Param("example") PaymentMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaymentMasterEntity record, @Param("example") PaymentMasterEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentMasterEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentmaster
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentMasterEntity record);
}