package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.PunishRecordEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.PunishRecordEntityExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PunishRecordEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    long countByExample(PunishRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int deleteByExample(PunishRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("terminalid") String terminalid, @Param("boxid") Integer boxid, @Param("usercardid") String usercardid, @Param("storeintime") Date storeintime, @Param("enddate") Date enddate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int insert(PunishRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int insertSelective(PunishRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    List<PunishRecordEntity> selectByExample(PunishRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    PunishRecordEntity selectByPrimaryKey(@Param("terminalid") String terminalid, @Param("boxid") Integer boxid, @Param("usercardid") String usercardid, @Param("storeintime") Date storeintime, @Param("enddate") Date enddate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PunishRecordEntity record, @Param("example") PunishRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PunishRecordEntity record, @Param("example") PunishRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PunishRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table punishrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PunishRecordEntity record);
}