package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.RemoteCtrlDiaryEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.RemoteCtrlDiaryEntityExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemoteCtrlDiaryEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    long countByExample(RemoteCtrlDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int deleteByExample(RemoteCtrlDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("accountcode") String accountcode, @Param("date") Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int insert(RemoteCtrlDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int insertSelective(RemoteCtrlDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    List<RemoteCtrlDiaryEntity> selectByExample(RemoteCtrlDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    RemoteCtrlDiaryEntity selectByPrimaryKey(@Param("accountcode") String accountcode, @Param("date") Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RemoteCtrlDiaryEntity record, @Param("example") RemoteCtrlDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RemoteCtrlDiaryEntity record, @Param("example") RemoteCtrlDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RemoteCtrlDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remotectrldiary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RemoteCtrlDiaryEntity record);
}