package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.RunTimeEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.RunTimeEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface RunTimeEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    long countByExample(RunTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int deleteByExample(RunTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer runtimecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int insert(RunTimeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int insertSelective(RunTimeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    List<RunTimeEntity> selectByExample(RunTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    RunTimeEntity selectByPrimaryKey(Integer runtimecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RunTimeEntity record, @Param("example") RunTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RunTimeEntity record, @Param("example") RunTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RunTimeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runtime
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RunTimeEntity record);

	@Select("SELECT * from runtime where runtimecode=(SELECT configvalue from businessmodel where configname="+"\"RunTime\""+" and businesscode=(SELECT Distinct businessmodel.businessCode from terminal,businessmodel"+
         " where terminal.businessCode=businessmodel.businessCode"+
            " and terminal.terminalID=#{terminalid}))")
	RunTimeEntity selectTime(@Param("terminalid") String terminalid);
}