package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.SystemInfoEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.SystemInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemInfoEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    long countByExample(SystemInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int deleteByExample(SystemInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String systemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int insert(SystemInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int insertSelective(SystemInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    List<SystemInfoEntity> selectByExample(SystemInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    SystemInfoEntity selectByPrimaryKey(String systemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemInfoEntity record, @Param("example") SystemInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemInfoEntity record, @Param("example") SystemInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systeminfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemInfoEntity record);
}