package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.TerminalWeixinEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.TerminalWeixinEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TerminalWeixinEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    long countByExample(TerminalWeixinEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int deleteByExample(TerminalWeixinEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String terminalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int insert(TerminalWeixinEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int insertSelective(TerminalWeixinEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    List<TerminalWeixinEntity> selectByExample(TerminalWeixinEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    TerminalWeixinEntity selectByPrimaryKey(String terminalid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TerminalWeixinEntity record, @Param("example") TerminalWeixinEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TerminalWeixinEntity record, @Param("example") TerminalWeixinEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TerminalWeixinEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalweixin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TerminalWeixinEntity record);
}