package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.TerminalAlarmDiaryEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.TerminalAlarmDiaryEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TerminalAlarmDiaryEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    long countByExample(TerminalAlarmDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int deleteByExample(TerminalAlarmDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String alarmcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int insert(TerminalAlarmDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int insertSelective(TerminalAlarmDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    List<TerminalAlarmDiaryEntity> selectByExample(TerminalAlarmDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    TerminalAlarmDiaryEntity selectByPrimaryKey(String alarmcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TerminalAlarmDiaryEntity record, @Param("example") TerminalAlarmDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TerminalAlarmDiaryEntity record, @Param("example") TerminalAlarmDiaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TerminalAlarmDiaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminalalarmdiary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TerminalAlarmDiaryEntity record);
}