package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.UserblacklistEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.UserblacklistEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserblacklistEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    long countByExample(UserblacklistEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int deleteByExample(UserblacklistEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String usercardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int insert(UserblacklistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int insertSelective(UserblacklistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    List<UserblacklistEntity> selectByExample(UserblacklistEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    UserblacklistEntity selectByPrimaryKey(String usercardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserblacklistEntity record, @Param("example") UserblacklistEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserblacklistEntity record, @Param("example") UserblacklistEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserblacklistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userblacklist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserblacklistEntity record);
}