package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.WeChatMessageEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.WeChatMessageEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeChatMessageEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    long countByExample(WeChatMessageEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int deleteByExample(WeChatMessageEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int insert(WeChatMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int insertSelective(WeChatMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    List<WeChatMessageEntity> selectByExample(WeChatMessageEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    WeChatMessageEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeChatMessageEntity record, @Param("example") WeChatMessageEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeChatMessageEntity record, @Param("example") WeChatMessageEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeChatMessageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeChatMessageEntity record);
}