package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.mapper;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.WxmenuEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.WxmenuEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxmenuEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    long countByExample(WxmenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int deleteByExample(WxmenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String codes);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int insert(WxmenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int insertSelective(WxmenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    List<WxmenuEntity> selectByExample(WxmenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    WxmenuEntity selectByPrimaryKey(String codes);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxmenuEntity record, @Param("example") WxmenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxmenuEntity record, @Param("example") WxmenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxmenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxmenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxmenuEntity record);
}