package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.custom.entity;

public class BoxAppExEntity {
    private String terminalid;
    private Integer boxid;
    private String dispalyname;
    private Integer boxtypecode;
    private Byte oneboxmorecard;
    private Byte fixedbox;
    private Byte article;
    private Byte open;
    private Byte status;
    private String displayname;
    private String tname;
    
    
    
    public String getTname() {
		return tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public String getDisplayname() {
		return displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.terminalID
     *
     * @return the value of box.terminalID
     *
     * @mbg.generated
     */
    public String getTerminalid() {
        return terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.terminalID
     *
     * @param terminalid the value for box.terminalID
     *
     * @mbg.generated
     */
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid == null ? null : terminalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.boxID
     *
     * @return the value of box.boxID
     *
     * @mbg.generated
     */
    public Integer getBoxid() {
        return boxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.boxID
     *
     * @param boxid the value for box.boxID
     *
     * @mbg.generated
     */
    public void setBoxid(Integer boxid) {
        this.boxid = boxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.dispalyName
     *
     * @return the value of box.dispalyName
     *
     * @mbg.generated
     */
    public String getDispalyname() {
        return dispalyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.dispalyName
     *
     * @param dispalyname the value for box.dispalyName
     *
     * @mbg.generated
     */
    public void setDispalyname(String dispalyname) {
        this.dispalyname = dispalyname == null ? null : dispalyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.boxTypeCode
     *
     * @return the value of box.boxTypeCode
     *
     * @mbg.generated
     */
    public Integer getBoxtypecode() {
        return boxtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.boxTypeCode
     *
     * @param boxtypecode the value for box.boxTypeCode
     *
     * @mbg.generated
     */
    public void setBoxtypecode(Integer boxtypecode) {
        this.boxtypecode = boxtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.oneBoxMoreCard
     *
     * @return the value of box.oneBoxMoreCard
     *
     * @mbg.generated
     */
    public Byte getOneboxmorecard() {
        return oneboxmorecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.oneBoxMoreCard
     *
     * @param oneboxmorecard the value for box.oneBoxMoreCard
     *
     * @mbg.generated
     */
    public void setOneboxmorecard(Byte oneboxmorecard) {
        this.oneboxmorecard = oneboxmorecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.fixedBox
     *
     * @return the value of box.fixedBox
     *
     * @mbg.generated
     */
    public Byte getFixedbox() {
        return fixedbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.fixedBox
     *
     * @param fixedbox the value for box.fixedBox
     *
     * @mbg.generated
     */
    public void setFixedbox(Byte fixedbox) {
        this.fixedbox = fixedbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.article
     *
     * @return the value of box.article
     *
     * @mbg.generated
     */
    public Byte getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.article
     *
     * @param article the value for box.article
     *
     * @mbg.generated
     */
    public void setArticle(Byte article) {
        this.article = article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.open
     *
     * @return the value of box.open
     *
     * @mbg.generated
     */
    public Byte getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.open
     *
     * @param open the value for box.open
     *
     * @mbg.generated
     */
    public void setOpen(Byte open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.status
     *
     * @return the value of box.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.status
     *
     * @param status the value for box.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}