package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.custom.entity;

import java.util.Date;

public class RemoteDeviceEx {
	    
	    private String terminalid;

	    private String areacode;

	    private Integer busBusinesscode;

	    private String configname;

	    private String displayname;

	    private Integer businesscode;

	    private String address;

	    private Integer totalboxnumber;

	    private String ipaddr;

	    private String macaddress;

	    private Byte runstatus;

	    private Byte networkstate;
	   
	    private String version;
	    
	    private String longitode;

	    private String dimension;
	   
	    private String registerflag;

	    private Date makedate;

	    private Date lastmodifytime;
	   
	    private String memo;
	  
	    private String makeopcode;
	    private Integer boxid;
	    private String dispalyname;
	    private Byte status;
	    private byte open;
	    
	   
	    public byte getOpen() {
			return open;
		}

		public void setOpen(byte open) {
			this.open = open;
		}

		public Byte getStatus() {
			return status;
		}

		public void setStatus(Byte status) {
			this.status = status;
		}

		public Integer getBoxid() {
			return boxid;
		}

		public void setBoxid(Integer boxid) {
			this.boxid = boxid;
		}

		public String getDispalyname() {
			return dispalyname;
		}

		public void setDispalyname(String dispalyname) {
			this.dispalyname = dispalyname;
		}

		public String getTerminalid() {
	        return terminalid;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.terminalID
	     *
	     * @param terminalid the value for terminal.terminalID
	     *
	     * @mbg.generated
	     */
	    public void setTerminalid(String terminalid) {
	        this.terminalid = terminalid == null ? null : terminalid.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.areaCode
	     *
	     * @return the value of terminal.areaCode
	     *
	     * @mbg.generated
	     */
	    public String getAreacode() {
	        return areacode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.areaCode
	     *
	     * @param areacode the value for terminal.areaCode
	     *
	     * @mbg.generated
	     */
	    public void setAreacode(String areacode) {
	        this.areacode = areacode == null ? null : areacode.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.Bus_businessCode
	     *
	     * @return the value of terminal.Bus_businessCode
	     *
	     * @mbg.generated
	     */
	    public Integer getBusBusinesscode() {
	        return busBusinesscode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.Bus_businessCode
	     *
	     * @param busBusinesscode the value for terminal.Bus_businessCode
	     *
	     * @mbg.generated
	     */
	    public void setBusBusinesscode(Integer busBusinesscode) {
	        this.busBusinesscode = busBusinesscode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.configName
	     *
	     * @return the value of terminal.configName
	     *
	     * @mbg.generated
	     */
	    public String getConfigname() {
	        return configname;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.configName
	     *
	     * @param configname the value for terminal.configName
	     *
	     * @mbg.generated
	     */
	    public void setConfigname(String configname) {
	        this.configname = configname == null ? null : configname.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.displayName
	     *
	     * @return the value of terminal.displayName
	     *
	     * @mbg.generated
	     */
	    public String getDisplayname() {
	        return displayname;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.displayName
	     *
	     * @param displayname the value for terminal.displayName
	     *
	     * @mbg.generated
	     */
	    public void setDisplayname(String displayname) {
	        this.displayname = displayname == null ? null : displayname.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.businessCode
	     *
	     * @return the value of terminal.businessCode
	     *
	     * @mbg.generated
	     */
	    public Integer getBusinesscode() {
	        return businesscode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.businessCode
	     *
	     * @param businesscode the value for terminal.businessCode
	     *
	     * @mbg.generated
	     */
	    public void setBusinesscode(Integer businesscode) {
	        this.businesscode = businesscode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.Address
	     *
	     * @return the value of terminal.Address
	     *
	     * @mbg.generated
	     */
	    public String getAddress() {
	        return address;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.Address
	     *
	     * @param address the value for terminal.Address
	     *
	     * @mbg.generated
	     */
	    public void setAddress(String address) {
	        this.address = address == null ? null : address.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.totalBoxNumber
	     *
	     * @return the value of terminal.totalBoxNumber
	     *
	     * @mbg.generated
	     */
	    public Integer getTotalboxnumber() {
	        return totalboxnumber;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.totalBoxNumber
	     *
	     * @param totalboxnumber the value for terminal.totalBoxNumber
	     *
	     * @mbg.generated
	     */
	    public void setTotalboxnumber(Integer totalboxnumber) {
	        this.totalboxnumber = totalboxnumber;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.IpAddr
	     *
	     * @return the value of terminal.IpAddr
	     *
	     * @mbg.generated
	     */
	    public String getIpaddr() {
	        return ipaddr;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.IpAddr
	     *
	     * @param ipaddr the value for terminal.IpAddr
	     *
	     * @mbg.generated
	     */
	    public void setIpaddr(String ipaddr) {
	        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.macAddress
	     *
	     * @return the value of terminal.macAddress
	     *
	     * @mbg.generated
	     */
	    public String getMacaddress() {
	        return macaddress;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.macAddress
	     *
	     * @param macaddress the value for terminal.macAddress
	     *
	     * @mbg.generated
	     */
	    public void setMacaddress(String macaddress) {
	        this.macaddress = macaddress == null ? null : macaddress.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.runStatus
	     *
	     * @return the value of terminal.runStatus
	     *
	     * @mbg.generated
	     */
	    public Byte getRunstatus() {
	        return runstatus;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.runStatus
	     *
	     * @param runstatus the value for terminal.runStatus
	     *
	     * @mbg.generated
	     */
	    public void setRunstatus(Byte runstatus) {
	        this.runstatus = runstatus;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.networkState
	     *
	     * @return the value of terminal.networkState
	     *
	     * @mbg.generated
	     */
	    public Byte getNetworkstate() {
	        return networkstate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.networkState
	     *
	     * @param networkstate the value for terminal.networkState
	     *
	     * @mbg.generated
	     */
	    public void setNetworkstate(Byte networkstate) {
	        this.networkstate = networkstate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.version
	     *
	     * @return the value of terminal.version
	     *
	     * @mbg.generated
	     */
	    public String getVersion() {
	        return version;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.version
	     *
	     * @param version the value for terminal.version
	     *
	     * @mbg.generated
	     */
	    public void setVersion(String version) {
	        this.version = version == null ? null : version.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.longitode
	     *
	     * @return the value of terminal.longitode
	     *
	     * @mbg.generated
	     */
	    public String getLongitode() {
	        return longitode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.longitode
	     *
	     * @param longitode the value for terminal.longitode
	     *
	     * @mbg.generated
	     */
	    public void setLongitode(String longitode) {
	        this.longitode = longitode == null ? null : longitode.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.dimension
	     *
	     * @return the value of terminal.dimension
	     *
	     * @mbg.generated
	     */
	    public String getDimension() {
	        return dimension;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.dimension
	     *
	     * @param dimension the value for terminal.dimension
	     *
	     * @mbg.generated
	     */
	    public void setDimension(String dimension) {
	        this.dimension = dimension == null ? null : dimension.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.registerFlag
	     *
	     * @return the value of terminal.registerFlag
	     *
	     * @mbg.generated
	     */
	    public String getRegisterflag() {
	        return registerflag;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.registerFlag
	     *
	     * @param registerflag the value for terminal.registerFlag
	     *
	     * @mbg.generated
	     */
	    public void setRegisterflag(String registerflag) {
	        this.registerflag = registerflag == null ? null : registerflag.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.makeDate
	     *
	     * @return the value of terminal.makeDate
	     *
	     * @mbg.generated
	     */
	    public Date getMakedate() {
	        return makedate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.makeDate
	     *
	     * @param makedate the value for terminal.makeDate
	     *
	     * @mbg.generated
	     */
	    public void setMakedate(Date makedate) {
	        this.makedate = makedate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.lastModifyTime
	     *
	     * @return the value of terminal.lastModifyTime
	     *
	     * @mbg.generated
	     */
	    public Date getLastmodifytime() {
	        return lastmodifytime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.lastModifyTime
	     *
	     * @param lastmodifytime the value for terminal.lastModifyTime
	     *
	     * @mbg.generated
	     */
	    public void setLastmodifytime(Date lastmodifytime) {
	        this.lastmodifytime = lastmodifytime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.memo
	     *
	     * @return the value of terminal.memo
	     *
	     * @mbg.generated
	     */
	    public String getMemo() {
	        return memo;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.memo
	     *
	     * @param memo the value for terminal.memo
	     *
	     * @mbg.generated
	     */
	    public void setMemo(String memo) {
	        this.memo = memo == null ? null : memo.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column terminal.makeOpCode
	     *
	     * @return the value of terminal.makeOpCode
	     *
	     * @mbg.generated
	     */
	    public String getMakeopcode() {
	        return makeopcode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column terminal.makeOpCode
	     *
	     * @param makeopcode the value for terminal.makeOpCode
	     *
	     * @mbg.generated
	     */
	    public void setMakeopcode(String makeopcode) {
	        this.makeopcode = makeopcode == null ? null : makeopcode.trim();
	    }
}
