package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.custom.entity;

import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.RunTimeEntity;
import com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity.UserEntity;

public class UserAndRuntimeBoundEx {	
	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column userandruntimebound.id
	     *
	     * @mbg.generated
	     */
	    private Integer id;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column userandruntimebound.userCardID
	     *
	     * @mbg.generated
	     */
	    private String usercardid;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column userandruntimebound.runTimeCode
	     *
	     * @mbg.generated
	     */
	    private Integer runtimecode;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column userandruntimebound.memo
	     *
	     * @mbg.generated
	     */
	    private String memo;
	    private RunTimeEntity runTimeEntity;
	    private UserEntity userEntity;
	    
	    

	    public RunTimeEntity getRunTimeEntity() {
			return runTimeEntity;
		}

		public void setRunTimeEntity(RunTimeEntity runTimeEntity) {
			this.runTimeEntity = runTimeEntity;
		}

		public UserEntity getUserEntity() {
			return userEntity;
		}

		public void setUserEntity(UserEntity userEntity) {
			this.userEntity = userEntity;
		}

		/**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column userandruntimebound.id
	     *
	     * @return the value of userandruntimebound.id
	     *
	     * @mbg.generated
	     */
	    public Integer getId() {
	        return id;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column userandruntimebound.id
	     *
	     * @param id the value for userandruntimebound.id
	     *
	     * @mbg.generated
	     */
	    public void setId(Integer id) {
	        this.id = id;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column userandruntimebound.userCardID
	     *
	     * @return the value of userandruntimebound.userCardID
	     *
	     * @mbg.generated
	     */
	    public String getUsercardid() {
	        return usercardid;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column userandruntimebound.userCardID
	     *
	     * @param usercardid the value for userandruntimebound.userCardID
	     *
	     * @mbg.generated
	     */
	    public void setUsercardid(String usercardid) {
	        this.usercardid = usercardid == null ? null : usercardid.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column userandruntimebound.runTimeCode
	     *
	     * @return the value of userandruntimebound.runTimeCode
	     *
	     * @mbg.generated
	     */
	    public Integer getRuntimecode() {
	        return runtimecode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column userandruntimebound.runTimeCode
	     *
	     * @param runtimecode the value for userandruntimebound.runTimeCode
	     *
	     * @mbg.generated
	     */
	    public void setRuntimecode(Integer runtimecode) {
	        this.runtimecode = runtimecode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column userandruntimebound.memo
	     *
	     * @return the value of userandruntimebound.memo
	     *
	     * @mbg.generated
	     */
	    public String getMemo() {
	        return memo;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column userandruntimebound.memo
	     *
	     * @param memo the value for userandruntimebound.memo
	     *
	     * @mbg.generated
	     */
	    public void setMemo(String memo) {
	        this.memo = memo == null ? null : memo.trim();
	    }
}
