package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

import java.util.Date;

public class AccountEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.accountCode
     *
     * @mbg.generated
     */
    private String accountcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.areaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.roleCode
     *
     * @mbg.generated
     */
    private Integer rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.accountName
     *
     * @mbg.generated
     */
    private String accountname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.EMail
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.makeDate
     *
     * @mbg.generated
     */
    private Date makedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.makeOpCode
     *
     * @mbg.generated
     */
    private String makeopcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastmodifytime;
    
    private Integer cashierflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.accountCode
     *
     * @return the value of account.accountCode
     *
     * @mbg.generated
     */
    public String getAccountcode() {
        return accountcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.accountCode
     *
     * @param accountcode the value for account.accountCode
     *
     * @mbg.generated
     */
    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode == null ? null : accountcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.areaCode
     *
     * @return the value of account.areaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.areaCode
     *
     * @param areacode the value for account.areaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.roleCode
     *
     * @return the value of account.roleCode
     *
     * @mbg.generated
     */
    public Integer getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.roleCode
     *
     * @param rolecode the value for account.roleCode
     *
     * @mbg.generated
     */
    public void setRolecode(Integer rolecode) {
        this.rolecode = rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.accountName
     *
     * @return the value of account.accountName
     *
     * @mbg.generated
     */
    public String getAccountname() {
        return accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.accountName
     *
     * @param accountname the value for account.accountName
     *
     * @mbg.generated
     */
    public void setAccountname(String accountname) {
        this.accountname = accountname == null ? null : accountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.address
     *
     * @return the value of account.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.address
     *
     * @param address the value for account.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.telephone
     *
     * @return the value of account.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.telephone
     *
     * @param telephone the value for account.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.EMail
     *
     * @return the value of account.EMail
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.EMail
     *
     * @param email the value for account.EMail
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.makeDate
     *
     * @return the value of account.makeDate
     *
     * @mbg.generated
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.makeDate
     *
     * @param makedate the value for account.makeDate
     *
     * @mbg.generated
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.makeOpCode
     *
     * @return the value of account.makeOpCode
     *
     * @mbg.generated
     */
    public String getMakeopcode() {
        return makeopcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.makeOpCode
     *
     * @param makeopcode the value for account.makeOpCode
     *
     * @mbg.generated
     */
    public void setMakeopcode(String makeopcode) {
        this.makeopcode = makeopcode == null ? null : makeopcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.memo
     *
     * @return the value of account.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.memo
     *
     * @param memo the value for account.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.lastModifyTime
     *
     * @return the value of account.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.lastModifyTime
     *
     * @param lastmodifytime the value for account.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

	public Integer getCashierflag() {
		return cashierflag;
	}

	public void setCashierflag(Integer cashierflag) {
		this.cashierflag = cashierflag;
	}
    
}