package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

public class AreaEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.areaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.areaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.areaShortName
     *
     * @mbg.generated
     */
    private String areashortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.appKey
     *
     * @mbg.generated
     */
    private String appkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.areaCode
     *
     * @return the value of area.areaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.areaCode
     *
     * @param areacode the value for area.areaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.areaName
     *
     * @return the value of area.areaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.areaName
     *
     * @param areaname the value for area.areaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.areaShortName
     *
     * @return the value of area.areaShortName
     *
     * @mbg.generated
     */
    public String getAreashortname() {
        return areashortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.areaShortName
     *
     * @param areashortname the value for area.areaShortName
     *
     * @mbg.generated
     */
    public void setAreashortname(String areashortname) {
        this.areashortname = areashortname == null ? null : areashortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.appKey
     *
     * @return the value of area.appKey
     *
     * @mbg.generated
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.appKey
     *
     * @param appkey the value for area.appKey
     *
     * @mbg.generated
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }
}