package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

import java.util.Date;

public class ManagerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.areaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerCardID
     *
     * @mbg.generated
     */
    private String managercardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerName
     *
     * @mbg.generated
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerType
     *
     * @mbg.generated
     */
    private Integer managertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.subDepartment
     *
     * @mbg.generated
     */
    private String subdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.endDate
     *
     * @mbg.generated
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.makeOpCode
     *
     * @mbg.generated
     */
    private String makeopcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.makeDate
     *
     * @mbg.generated
     */
    private Date makedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastmodifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.areaCode
     *
     * @return the value of manager.areaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.areaCode
     *
     * @param areacode the value for manager.areaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerCardID
     *
     * @return the value of manager.managerCardID
     *
     * @mbg.generated
     */
    public String getManagercardid() {
        return managercardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerCardID
     *
     * @param managercardid the value for manager.managerCardID
     *
     * @mbg.generated
     */
    public void setManagercardid(String managercardid) {
        this.managercardid = managercardid == null ? null : managercardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerName
     *
     * @return the value of manager.managerName
     *
     * @mbg.generated
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerName
     *
     * @param managername the value for manager.managerName
     *
     * @mbg.generated
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerType
     *
     * @return the value of manager.managerType
     *
     * @mbg.generated
     */
    public Integer getManagertype() {
        return managertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerType
     *
     * @param managertype the value for manager.managerType
     *
     * @mbg.generated
     */
    public void setManagertype(Integer managertype) {
        this.managertype = managertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.sex
     *
     * @return the value of manager.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.sex
     *
     * @param sex the value for manager.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.telephone
     *
     * @return the value of manager.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.telephone
     *
     * @param telephone the value for manager.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.company
     *
     * @return the value of manager.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.company
     *
     * @param company the value for manager.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.department
     *
     * @return the value of manager.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.department
     *
     * @param department the value for manager.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.subDepartment
     *
     * @return the value of manager.subDepartment
     *
     * @mbg.generated
     */
    public String getSubdepartment() {
        return subdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.subDepartment
     *
     * @param subdepartment the value for manager.subDepartment
     *
     * @mbg.generated
     */
    public void setSubdepartment(String subdepartment) {
        this.subdepartment = subdepartment == null ? null : subdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.endDate
     *
     * @return the value of manager.endDate
     *
     * @mbg.generated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.endDate
     *
     * @param enddate the value for manager.endDate
     *
     * @mbg.generated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.state
     *
     * @return the value of manager.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.state
     *
     * @param state the value for manager.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.makeOpCode
     *
     * @return the value of manager.makeOpCode
     *
     * @mbg.generated
     */
    public String getMakeopcode() {
        return makeopcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.makeOpCode
     *
     * @param makeopcode the value for manager.makeOpCode
     *
     * @mbg.generated
     */
    public void setMakeopcode(String makeopcode) {
        this.makeopcode = makeopcode == null ? null : makeopcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.makeDate
     *
     * @return the value of manager.makeDate
     *
     * @mbg.generated
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.makeDate
     *
     * @param makedate the value for manager.makeDate
     *
     * @mbg.generated
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.lastModifyTime
     *
     * @return the value of manager.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.lastModifyTime
     *
     * @param lastmodifytime the value for manager.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.memo
     *
     * @return the value of manager.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.memo
     *
     * @param memo the value for manager.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}