package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

public class MenuRightsEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column menurights.menuCode
	 *
	 * @mbg.generated
	 */
	private String menucode;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column menurights.roleCode
	 *
	 * @mbg.generated
	 */
	private Integer rolecode;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column menurights.menuAccess
	 *
	 * @mbg.generated
	 */
	private String menuaccess;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column menurights.menuOperator
	 *
	 * @mbg.generated
	 */
	private String menuoperator;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column menurights.menuAuthorize
	 *
	 * @mbg.generated
	 */
	private String menuauthorize;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column menurights.menuCode
	 *
	 * @return the value of menurights.menuCode
	 *
	 * @mbg.generated
	 */
	public String getMenucode() {
		return menucode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column menurights.menuCode
	 *
	 * @param menucode the value for menurights.menuCode
	 *
	 * @mbg.generated
	 */
	public void setMenucode(String menucode) {
		this.menucode = menucode == null ? null : menucode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column menurights.roleCode
	 *
	 * @return the value of menurights.roleCode
	 *
	 * @mbg.generated
	 */
	public Integer getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column menurights.roleCode
	 *
	 * @param rolecode the value for menurights.roleCode
	 *
	 * @mbg.generated
	 */
	public void setRolecode(Integer rolecode) {
		this.rolecode = rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column menurights.menuAccess
	 *
	 * @return the value of menurights.menuAccess
	 *
	 * @mbg.generated
	 */
	public String getMenuaccess() {
		return menuaccess;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column menurights.menuAccess
	 *
	 * @param menuaccess the value for menurights.menuAccess
	 *
	 * @mbg.generated
	 */
	public void setMenuaccess(String menuaccess) {
		this.menuaccess = menuaccess == null ? null : menuaccess.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column menurights.menuOperator
	 *
	 * @return the value of menurights.menuOperator
	 *
	 * @mbg.generated
	 */
	public String getMenuoperator() {
		return menuoperator;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column menurights.menuOperator
	 *
	 * @param menuoperator the value for menurights.menuOperator
	 *
	 * @mbg.generated
	 */
	public void setMenuoperator(String menuoperator) {
		this.menuoperator = menuoperator == null ? null : menuoperator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column menurights.menuAuthorize
	 *
	 * @return the value of menurights.menuAuthorize
	 *
	 * @mbg.generated
	 */
	public String getMenuauthorize() {
		return menuauthorize;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column menurights.menuAuthorize
	 *
	 * @param menuauthorize the value for menurights.menuAuthorize
	 *
	 * @mbg.generated
	 */
	public void setMenuauthorize(String menuauthorize) {
		this.menuauthorize = menuauthorize == null ? null : menuauthorize.trim();
	}

}