package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PtreadypackageEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.TerminalNo
     *
     * @mbg.generated
     */
    private String terminalno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.PackageID
     *
     * @mbg.generated
     */
    private String packageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.OrderTime
     *
     * @mbg.generated
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.ExpiredTime
     *
     * @mbg.generated
     */
    private Date expiredtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.PostmanID
     *
     * @mbg.generated
     */
    private String postmanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.CompanyID
     *
     * @mbg.generated
     */
    private String companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.BoxNo
     *
     * @mbg.generated
     */
    private String boxno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.CustomerID
     *
     * @mbg.generated
     */
    private String customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.CustomerMobile
     *
     * @mbg.generated
     */
    private String customermobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.CustomerName
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.CustomerAddress
     *
     * @mbg.generated
     */
    private String customeraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.HireAmt
     *
     * @mbg.generated
     */
    private BigDecimal hireamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.HireWhoPay
     *
     * @mbg.generated
     */
    private String hirewhopay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.PosPayFlag
     *
     * @mbg.generated
     */
    private String pospayflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.PayAmt
     *
     * @mbg.generated
     */
    private BigDecimal payamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.PackageStatus
     *
     * @mbg.generated
     */
    private String packagestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.LastModifyTime
     *
     * @mbg.generated
     */
    private Date lastmodifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.Remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.PayStatus
     *
     * @mbg.generated
     */
    private Byte paystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.TradeWaterNo
     *
     * @mbg.generated
     */
    private String tradewaterno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.storeInTime
     *
     * @mbg.generated
     */
    private Date storeintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.takeTime
     *
     * @mbg.generated
     */
    private Date taketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.TradeWaterNoRemain
     *
     * @mbg.generated
     */
    private String tradewaternoremain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.OpenStatus
     *
     * @mbg.generated
     */
    private Byte openstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.LimitCounts
     *
     * @mbg.generated
     */
    private Integer limitcounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.LimitCountsTake
     *
     * @mbg.generated
     */
    private Integer limitcountstake;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.TradeWaterNotwo
     *
     * @mbg.generated
     */
    private String tradewaternotwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.TradeWaterNothree
     *
     * @mbg.generated
     */
    private String tradewaternothree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptreadypackage.TradeWaterNofour
     *
     * @mbg.generated
     */
    private String tradewaternofour;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.TerminalNo
     *
     * @return the value of ptreadypackage.TerminalNo
     *
     * @mbg.generated
     */
    public String getTerminalno() {
        return terminalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.TerminalNo
     *
     * @param terminalno the value for ptreadypackage.TerminalNo
     *
     * @mbg.generated
     */
    public void setTerminalno(String terminalno) {
        this.terminalno = terminalno == null ? null : terminalno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.PackageID
     *
     * @return the value of ptreadypackage.PackageID
     *
     * @mbg.generated
     */
    public String getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.PackageID
     *
     * @param packageid the value for ptreadypackage.PackageID
     *
     * @mbg.generated
     */
    public void setPackageid(String packageid) {
        this.packageid = packageid == null ? null : packageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.OrderTime
     *
     * @return the value of ptreadypackage.OrderTime
     *
     * @mbg.generated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.OrderTime
     *
     * @param ordertime the value for ptreadypackage.OrderTime
     *
     * @mbg.generated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.ExpiredTime
     *
     * @return the value of ptreadypackage.ExpiredTime
     *
     * @mbg.generated
     */
    public Date getExpiredtime() {
        return expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.ExpiredTime
     *
     * @param expiredtime the value for ptreadypackage.ExpiredTime
     *
     * @mbg.generated
     */
    public void setExpiredtime(Date expiredtime) {
        this.expiredtime = expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.PostmanID
     *
     * @return the value of ptreadypackage.PostmanID
     *
     * @mbg.generated
     */
    public String getPostmanid() {
        return postmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.PostmanID
     *
     * @param postmanid the value for ptreadypackage.PostmanID
     *
     * @mbg.generated
     */
    public void setPostmanid(String postmanid) {
        this.postmanid = postmanid == null ? null : postmanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.CompanyID
     *
     * @return the value of ptreadypackage.CompanyID
     *
     * @mbg.generated
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.CompanyID
     *
     * @param companyid the value for ptreadypackage.CompanyID
     *
     * @mbg.generated
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.BoxNo
     *
     * @return the value of ptreadypackage.BoxNo
     *
     * @mbg.generated
     */
    public String getBoxno() {
        return boxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.BoxNo
     *
     * @param boxno the value for ptreadypackage.BoxNo
     *
     * @mbg.generated
     */
    public void setBoxno(String boxno) {
        this.boxno = boxno == null ? null : boxno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.CustomerID
     *
     * @return the value of ptreadypackage.CustomerID
     *
     * @mbg.generated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.CustomerID
     *
     * @param customerid the value for ptreadypackage.CustomerID
     *
     * @mbg.generated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.CustomerMobile
     *
     * @return the value of ptreadypackage.CustomerMobile
     *
     * @mbg.generated
     */
    public String getCustomermobile() {
        return customermobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.CustomerMobile
     *
     * @param customermobile the value for ptreadypackage.CustomerMobile
     *
     * @mbg.generated
     */
    public void setCustomermobile(String customermobile) {
        this.customermobile = customermobile == null ? null : customermobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.CustomerName
     *
     * @return the value of ptreadypackage.CustomerName
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.CustomerName
     *
     * @param customername the value for ptreadypackage.CustomerName
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.CustomerAddress
     *
     * @return the value of ptreadypackage.CustomerAddress
     *
     * @mbg.generated
     */
    public String getCustomeraddress() {
        return customeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.CustomerAddress
     *
     * @param customeraddress the value for ptreadypackage.CustomerAddress
     *
     * @mbg.generated
     */
    public void setCustomeraddress(String customeraddress) {
        this.customeraddress = customeraddress == null ? null : customeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.HireAmt
     *
     * @return the value of ptreadypackage.HireAmt
     *
     * @mbg.generated
     */
    public BigDecimal getHireamt() {
        return hireamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.HireAmt
     *
     * @param hireamt the value for ptreadypackage.HireAmt
     *
     * @mbg.generated
     */
    public void setHireamt(BigDecimal hireamt) {
        this.hireamt = hireamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.HireWhoPay
     *
     * @return the value of ptreadypackage.HireWhoPay
     *
     * @mbg.generated
     */
    public String getHirewhopay() {
        return hirewhopay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.HireWhoPay
     *
     * @param hirewhopay the value for ptreadypackage.HireWhoPay
     *
     * @mbg.generated
     */
    public void setHirewhopay(String hirewhopay) {
        this.hirewhopay = hirewhopay == null ? null : hirewhopay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.PosPayFlag
     *
     * @return the value of ptreadypackage.PosPayFlag
     *
     * @mbg.generated
     */
    public String getPospayflag() {
        return pospayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.PosPayFlag
     *
     * @param pospayflag the value for ptreadypackage.PosPayFlag
     *
     * @mbg.generated
     */
    public void setPospayflag(String pospayflag) {
        this.pospayflag = pospayflag == null ? null : pospayflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.PayAmt
     *
     * @return the value of ptreadypackage.PayAmt
     *
     * @mbg.generated
     */
    public BigDecimal getPayamt() {
        return payamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.PayAmt
     *
     * @param payamt the value for ptreadypackage.PayAmt
     *
     * @mbg.generated
     */
    public void setPayamt(BigDecimal payamt) {
        this.payamt = payamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.PackageStatus
     *
     * @return the value of ptreadypackage.PackageStatus
     *
     * @mbg.generated
     */
    public String getPackagestatus() {
        return packagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.PackageStatus
     *
     * @param packagestatus the value for ptreadypackage.PackageStatus
     *
     * @mbg.generated
     */
    public void setPackagestatus(String packagestatus) {
        this.packagestatus = packagestatus == null ? null : packagestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.LastModifyTime
     *
     * @return the value of ptreadypackage.LastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.LastModifyTime
     *
     * @param lastmodifytime the value for ptreadypackage.LastModifyTime
     *
     * @mbg.generated
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.Remark
     *
     * @return the value of ptreadypackage.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.Remark
     *
     * @param remark the value for ptreadypackage.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.PayStatus
     *
     * @return the value of ptreadypackage.PayStatus
     *
     * @mbg.generated
     */
    public Byte getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.PayStatus
     *
     * @param paystatus the value for ptreadypackage.PayStatus
     *
     * @mbg.generated
     */
    public void setPaystatus(Byte paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.TradeWaterNo
     *
     * @return the value of ptreadypackage.TradeWaterNo
     *
     * @mbg.generated
     */
    public String getTradewaterno() {
        return tradewaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.TradeWaterNo
     *
     * @param tradewaterno the value for ptreadypackage.TradeWaterNo
     *
     * @mbg.generated
     */
    public void setTradewaterno(String tradewaterno) {
        this.tradewaterno = tradewaterno == null ? null : tradewaterno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.storeInTime
     *
     * @return the value of ptreadypackage.storeInTime
     *
     * @mbg.generated
     */
    public Date getStoreintime() {
        return storeintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.storeInTime
     *
     * @param storeintime the value for ptreadypackage.storeInTime
     *
     * @mbg.generated
     */
    public void setStoreintime(Date storeintime) {
        this.storeintime = storeintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.takeTime
     *
     * @return the value of ptreadypackage.takeTime
     *
     * @mbg.generated
     */
    public Date getTaketime() {
        return taketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.takeTime
     *
     * @param taketime the value for ptreadypackage.takeTime
     *
     * @mbg.generated
     */
    public void setTaketime(Date taketime) {
        this.taketime = taketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.TradeWaterNoRemain
     *
     * @return the value of ptreadypackage.TradeWaterNoRemain
     *
     * @mbg.generated
     */
    public String getTradewaternoremain() {
        return tradewaternoremain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.TradeWaterNoRemain
     *
     * @param tradewaternoremain the value for ptreadypackage.TradeWaterNoRemain
     *
     * @mbg.generated
     */
    public void setTradewaternoremain(String tradewaternoremain) {
        this.tradewaternoremain = tradewaternoremain == null ? null : tradewaternoremain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.OpenStatus
     *
     * @return the value of ptreadypackage.OpenStatus
     *
     * @mbg.generated
     */
    public Byte getOpenstatus() {
        return openstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.OpenStatus
     *
     * @param openstatus the value for ptreadypackage.OpenStatus
     *
     * @mbg.generated
     */
    public void setOpenstatus(Byte openstatus) {
        this.openstatus = openstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.LimitCounts
     *
     * @return the value of ptreadypackage.LimitCounts
     *
     * @mbg.generated
     */
    public Integer getLimitcounts() {
        return limitcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.LimitCounts
     *
     * @param limitcounts the value for ptreadypackage.LimitCounts
     *
     * @mbg.generated
     */
    public void setLimitcounts(Integer limitcounts) {
        this.limitcounts = limitcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.LimitCountsTake
     *
     * @return the value of ptreadypackage.LimitCountsTake
     *
     * @mbg.generated
     */
    public Integer getLimitcountstake() {
        return limitcountstake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.LimitCountsTake
     *
     * @param limitcountstake the value for ptreadypackage.LimitCountsTake
     *
     * @mbg.generated
     */
    public void setLimitcountstake(Integer limitcountstake) {
        this.limitcountstake = limitcountstake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.TradeWaterNotwo
     *
     * @return the value of ptreadypackage.TradeWaterNotwo
     *
     * @mbg.generated
     */
    public String getTradewaternotwo() {
        return tradewaternotwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.TradeWaterNotwo
     *
     * @param tradewaternotwo the value for ptreadypackage.TradeWaterNotwo
     *
     * @mbg.generated
     */
    public void setTradewaternotwo(String tradewaternotwo) {
        this.tradewaternotwo = tradewaternotwo == null ? null : tradewaternotwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.TradeWaterNothree
     *
     * @return the value of ptreadypackage.TradeWaterNothree
     *
     * @mbg.generated
     */
    public String getTradewaternothree() {
        return tradewaternothree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.TradeWaterNothree
     *
     * @param tradewaternothree the value for ptreadypackage.TradeWaterNothree
     *
     * @mbg.generated
     */
    public void setTradewaternothree(String tradewaternothree) {
        this.tradewaternothree = tradewaternothree == null ? null : tradewaternothree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptreadypackage.TradeWaterNofour
     *
     * @return the value of ptreadypackage.TradeWaterNofour
     *
     * @mbg.generated
     */
    public String getTradewaternofour() {
        return tradewaternofour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptreadypackage.TradeWaterNofour
     *
     * @param tradewaternofour the value for ptreadypackage.TradeWaterNofour
     *
     * @mbg.generated
     */
    public void setTradewaternofour(String tradewaternofour) {
        this.tradewaternofour = tradewaternofour == null ? null : tradewaternofour.trim();
    }
}