package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

import java.util.Date;

public class TerminalAlarmDiaryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.alarmCode
     *
     * @mbg.generated
     */
    private String alarmcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.terminalID
     *
     * @mbg.generated
     */
    private String terminalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.alarmDate
     *
     * @mbg.generated
     */
    private Date alarmdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.alarmType
     *
     * @mbg.generated
     */
    private Integer alarmtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.handlOpCode
     *
     * @mbg.generated
     */
    private String handlopcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.handleDate
     *
     * @mbg.generated
     */
    private Date handledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.handleContent
     *
     * @mbg.generated
     */
    private String handlecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.handleResult
     *
     * @mbg.generated
     */
    private String handleresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.fileOpCode
     *
     * @mbg.generated
     */
    private String fileopcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.fileDate
     *
     * @mbg.generated
     */
    private Date filedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.fileType
     *
     * @mbg.generated
     */
    private Integer filetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalalarmdiary.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.alarmCode
     *
     * @return the value of terminalalarmdiary.alarmCode
     *
     * @mbg.generated
     */
    public String getAlarmcode() {
        return alarmcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.alarmCode
     *
     * @param alarmcode the value for terminalalarmdiary.alarmCode
     *
     * @mbg.generated
     */
    public void setAlarmcode(String alarmcode) {
        this.alarmcode = alarmcode == null ? null : alarmcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.terminalID
     *
     * @return the value of terminalalarmdiary.terminalID
     *
     * @mbg.generated
     */
    public String getTerminalid() {
        return terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.terminalID
     *
     * @param terminalid the value for terminalalarmdiary.terminalID
     *
     * @mbg.generated
     */
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid == null ? null : terminalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.alarmDate
     *
     * @return the value of terminalalarmdiary.alarmDate
     *
     * @mbg.generated
     */
    public Date getAlarmdate() {
        return alarmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.alarmDate
     *
     * @param alarmdate the value for terminalalarmdiary.alarmDate
     *
     * @mbg.generated
     */
    public void setAlarmdate(Date alarmdate) {
        this.alarmdate = alarmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.alarmType
     *
     * @return the value of terminalalarmdiary.alarmType
     *
     * @mbg.generated
     */
    public Integer getAlarmtype() {
        return alarmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.alarmType
     *
     * @param alarmtype the value for terminalalarmdiary.alarmType
     *
     * @mbg.generated
     */
    public void setAlarmtype(Integer alarmtype) {
        this.alarmtype = alarmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.content
     *
     * @return the value of terminalalarmdiary.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.content
     *
     * @param content the value for terminalalarmdiary.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.state
     *
     * @return the value of terminalalarmdiary.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.state
     *
     * @param state the value for terminalalarmdiary.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.handlOpCode
     *
     * @return the value of terminalalarmdiary.handlOpCode
     *
     * @mbg.generated
     */
    public String getHandlopcode() {
        return handlopcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.handlOpCode
     *
     * @param handlopcode the value for terminalalarmdiary.handlOpCode
     *
     * @mbg.generated
     */
    public void setHandlopcode(String handlopcode) {
        this.handlopcode = handlopcode == null ? null : handlopcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.handleDate
     *
     * @return the value of terminalalarmdiary.handleDate
     *
     * @mbg.generated
     */
    public Date getHandledate() {
        return handledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.handleDate
     *
     * @param handledate the value for terminalalarmdiary.handleDate
     *
     * @mbg.generated
     */
    public void setHandledate(Date handledate) {
        this.handledate = handledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.handleContent
     *
     * @return the value of terminalalarmdiary.handleContent
     *
     * @mbg.generated
     */
    public String getHandlecontent() {
        return handlecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.handleContent
     *
     * @param handlecontent the value for terminalalarmdiary.handleContent
     *
     * @mbg.generated
     */
    public void setHandlecontent(String handlecontent) {
        this.handlecontent = handlecontent == null ? null : handlecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.handleResult
     *
     * @return the value of terminalalarmdiary.handleResult
     *
     * @mbg.generated
     */
    public String getHandleresult() {
        return handleresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.handleResult
     *
     * @param handleresult the value for terminalalarmdiary.handleResult
     *
     * @mbg.generated
     */
    public void setHandleresult(String handleresult) {
        this.handleresult = handleresult == null ? null : handleresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.fileOpCode
     *
     * @return the value of terminalalarmdiary.fileOpCode
     *
     * @mbg.generated
     */
    public String getFileopcode() {
        return fileopcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.fileOpCode
     *
     * @param fileopcode the value for terminalalarmdiary.fileOpCode
     *
     * @mbg.generated
     */
    public void setFileopcode(String fileopcode) {
        this.fileopcode = fileopcode == null ? null : fileopcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.fileDate
     *
     * @return the value of terminalalarmdiary.fileDate
     *
     * @mbg.generated
     */
    public Date getFiledate() {
        return filedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.fileDate
     *
     * @param filedate the value for terminalalarmdiary.fileDate
     *
     * @mbg.generated
     */
    public void setFiledate(Date filedate) {
        this.filedate = filedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.fileType
     *
     * @return the value of terminalalarmdiary.fileType
     *
     * @mbg.generated
     */
    public Integer getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.fileType
     *
     * @param filetype the value for terminalalarmdiary.fileType
     *
     * @mbg.generated
     */
    public void setFiletype(Integer filetype) {
        this.filetype = filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalalarmdiary.memo
     *
     * @return the value of terminalalarmdiary.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalalarmdiary.memo
     *
     * @param memo the value for terminalalarmdiary.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}