package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

public class TerminalWeixinEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalweixin.terminalID
     *
     * @mbg.generated
     */
    private String terminalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminalweixin.qrcodeUrls
     *
     * @mbg.generated
     */
    private String qrcodeurls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalweixin.terminalID
     *
     * @return the value of terminalweixin.terminalID
     *
     * @mbg.generated
     */
    public String getTerminalid() {
        return terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalweixin.terminalID
     *
     * @param terminalid the value for terminalweixin.terminalID
     *
     * @mbg.generated
     */
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid == null ? null : terminalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminalweixin.qrcodeUrls
     *
     * @return the value of terminalweixin.qrcodeUrls
     *
     * @mbg.generated
     */
    public String getQrcodeurls() {
        return qrcodeurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminalweixin.qrcodeUrls
     *
     * @param qrcodeurls the value for terminalweixin.qrcodeUrls
     *
     * @mbg.generated
     */
    public void setQrcodeurls(String qrcodeurls) {
        this.qrcodeurls = qrcodeurls == null ? null : qrcodeurls.trim();
    }
}