package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TerminalEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table terminal
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table terminal
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table terminal
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public TerminalEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table terminal
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTerminalidIsNull() {
            addCriterion("terminalID is null");
            return (Criteria) this;
        }

        public Criteria andTerminalidIsNotNull() {
            addCriterion("terminalID is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalidEqualTo(String value) {
            addCriterion("terminalID =", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidNotEqualTo(String value) {
            addCriterion("terminalID <>", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidGreaterThan(String value) {
            addCriterion("terminalID >", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidGreaterThanOrEqualTo(String value) {
            addCriterion("terminalID >=", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidLessThan(String value) {
            addCriterion("terminalID <", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidLessThanOrEqualTo(String value) {
            addCriterion("terminalID <=", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidLike(String value) {
            addCriterion("terminalID like", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidNotLike(String value) {
            addCriterion("terminalID not like", value, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidIn(List<String> values) {
            addCriterion("terminalID in", values, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidNotIn(List<String> values) {
            addCriterion("terminalID not in", values, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidBetween(String value1, String value2) {
            addCriterion("terminalID between", value1, value2, "terminalid");
            return (Criteria) this;
        }

        public Criteria andTerminalidNotBetween(String value1, String value2) {
            addCriterion("terminalID not between", value1, value2, "terminalid");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNull() {
            addCriterion("areaCode is null");
            return (Criteria) this;
        }

        public Criteria andAreacodeIsNotNull() {
            addCriterion("areaCode is not null");
            return (Criteria) this;
        }

        public Criteria andAreacodeEqualTo(String value) {
            addCriterion("areaCode =", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotEqualTo(String value) {
            addCriterion("areaCode <>", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThan(String value) {
            addCriterion("areaCode >", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeGreaterThanOrEqualTo(String value) {
            addCriterion("areaCode >=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThan(String value) {
            addCriterion("areaCode <", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLessThanOrEqualTo(String value) {
            addCriterion("areaCode <=", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeLike(String value) {
            addCriterion("areaCode like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotLike(String value) {
            addCriterion("areaCode not like", value, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeIn(List<String> values) {
            addCriterion("areaCode in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotIn(List<String> values) {
            addCriterion("areaCode not in", values, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeBetween(String value1, String value2) {
            addCriterion("areaCode between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andAreacodeNotBetween(String value1, String value2) {
            addCriterion("areaCode not between", value1, value2, "areacode");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIsNull() {
            addCriterion("displayName is null");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIsNotNull() {
            addCriterion("displayName is not null");
            return (Criteria) this;
        }

        public Criteria andDisplaynameEqualTo(String value) {
            addCriterion("displayName =", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotEqualTo(String value) {
            addCriterion("displayName <>", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameGreaterThan(String value) {
            addCriterion("displayName >", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameGreaterThanOrEqualTo(String value) {
            addCriterion("displayName >=", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLessThan(String value) {
            addCriterion("displayName <", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLessThanOrEqualTo(String value) {
            addCriterion("displayName <=", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLike(String value) {
            addCriterion("displayName like", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotLike(String value) {
            addCriterion("displayName not like", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIn(List<String> values) {
            addCriterion("displayName in", values, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotIn(List<String> values) {
            addCriterion("displayName not in", values, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameBetween(String value1, String value2) {
            addCriterion("displayName between", value1, value2, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotBetween(String value1, String value2) {
            addCriterion("displayName not between", value1, value2, "displayname");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberIsNull() {
            addCriterion("totalBoxNumber is null");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberIsNotNull() {
            addCriterion("totalBoxNumber is not null");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberEqualTo(Integer value) {
            addCriterion("totalBoxNumber =", value, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberNotEqualTo(Integer value) {
            addCriterion("totalBoxNumber <>", value, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberGreaterThan(Integer value) {
            addCriterion("totalBoxNumber >", value, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("totalBoxNumber >=", value, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberLessThan(Integer value) {
            addCriterion("totalBoxNumber <", value, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberLessThanOrEqualTo(Integer value) {
            addCriterion("totalBoxNumber <=", value, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberIn(List<Integer> values) {
            addCriterion("totalBoxNumber in", values, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberNotIn(List<Integer> values) {
            addCriterion("totalBoxNumber not in", values, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberBetween(Integer value1, Integer value2) {
            addCriterion("totalBoxNumber between", value1, value2, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andTotalboxnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("totalBoxNumber not between", value1, value2, "totalboxnumber");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeIsNull() {
            addCriterion("businessCode is null");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeIsNotNull() {
            addCriterion("businessCode is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeEqualTo(Integer value) {
            addCriterion("businessCode =", value, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeNotEqualTo(Integer value) {
            addCriterion("businessCode <>", value, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeGreaterThan(Integer value) {
            addCriterion("businessCode >", value, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("businessCode >=", value, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeLessThan(Integer value) {
            addCriterion("businessCode <", value, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeLessThanOrEqualTo(Integer value) {
            addCriterion("businessCode <=", value, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeIn(List<Integer> values) {
            addCriterion("businessCode in", values, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeNotIn(List<Integer> values) {
            addCriterion("businessCode not in", values, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeBetween(Integer value1, Integer value2) {
            addCriterion("businessCode between", value1, value2, "businesscode");
            return (Criteria) this;
        }

        public Criteria andBusinesscodeNotBetween(Integer value1, Integer value2) {
            addCriterion("businessCode not between", value1, value2, "businesscode");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("Address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("Address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andIpaddrIsNull() {
            addCriterion("IpAddr is null");
            return (Criteria) this;
        }

        public Criteria andIpaddrIsNotNull() {
            addCriterion("IpAddr is not null");
            return (Criteria) this;
        }

        public Criteria andIpaddrEqualTo(String value) {
            addCriterion("IpAddr =", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotEqualTo(String value) {
            addCriterion("IpAddr <>", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrGreaterThan(String value) {
            addCriterion("IpAddr >", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrGreaterThanOrEqualTo(String value) {
            addCriterion("IpAddr >=", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrLessThan(String value) {
            addCriterion("IpAddr <", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrLessThanOrEqualTo(String value) {
            addCriterion("IpAddr <=", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrLike(String value) {
            addCriterion("IpAddr like", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotLike(String value) {
            addCriterion("IpAddr not like", value, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrIn(List<String> values) {
            addCriterion("IpAddr in", values, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotIn(List<String> values) {
            addCriterion("IpAddr not in", values, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrBetween(String value1, String value2) {
            addCriterion("IpAddr between", value1, value2, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andIpaddrNotBetween(String value1, String value2) {
            addCriterion("IpAddr not between", value1, value2, "ipaddr");
            return (Criteria) this;
        }

        public Criteria andMacaddressIsNull() {
            addCriterion("macAddress is null");
            return (Criteria) this;
        }

        public Criteria andMacaddressIsNotNull() {
            addCriterion("macAddress is not null");
            return (Criteria) this;
        }

        public Criteria andMacaddressEqualTo(String value) {
            addCriterion("macAddress =", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressNotEqualTo(String value) {
            addCriterion("macAddress <>", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressGreaterThan(String value) {
            addCriterion("macAddress >", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressGreaterThanOrEqualTo(String value) {
            addCriterion("macAddress >=", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressLessThan(String value) {
            addCriterion("macAddress <", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressLessThanOrEqualTo(String value) {
            addCriterion("macAddress <=", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressLike(String value) {
            addCriterion("macAddress like", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressNotLike(String value) {
            addCriterion("macAddress not like", value, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressIn(List<String> values) {
            addCriterion("macAddress in", values, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressNotIn(List<String> values) {
            addCriterion("macAddress not in", values, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressBetween(String value1, String value2) {
            addCriterion("macAddress between", value1, value2, "macaddress");
            return (Criteria) this;
        }

        public Criteria andMacaddressNotBetween(String value1, String value2) {
            addCriterion("macAddress not between", value1, value2, "macaddress");
            return (Criteria) this;
        }

        public Criteria andRunstatusIsNull() {
            addCriterion("runStatus is null");
            return (Criteria) this;
        }

        public Criteria andRunstatusIsNotNull() {
            addCriterion("runStatus is not null");
            return (Criteria) this;
        }

        public Criteria andRunstatusEqualTo(Byte value) {
            addCriterion("runStatus =", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotEqualTo(Byte value) {
            addCriterion("runStatus <>", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusGreaterThan(Byte value) {
            addCriterion("runStatus >", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("runStatus >=", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusLessThan(Byte value) {
            addCriterion("runStatus <", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusLessThanOrEqualTo(Byte value) {
            addCriterion("runStatus <=", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusIn(List<Byte> values) {
            addCriterion("runStatus in", values, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotIn(List<Byte> values) {
            addCriterion("runStatus not in", values, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusBetween(Byte value1, Byte value2) {
            addCriterion("runStatus between", value1, value2, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotBetween(Byte value1, Byte value2) {
            addCriterion("runStatus not between", value1, value2, "runstatus");
            return (Criteria) this;
        }

        public Criteria andNetworkstateIsNull() {
            addCriterion("networkState is null");
            return (Criteria) this;
        }

        public Criteria andNetworkstateIsNotNull() {
            addCriterion("networkState is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkstateEqualTo(Byte value) {
            addCriterion("networkState =", value, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateNotEqualTo(Byte value) {
            addCriterion("networkState <>", value, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateGreaterThan(Byte value) {
            addCriterion("networkState >", value, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateGreaterThanOrEqualTo(Byte value) {
            addCriterion("networkState >=", value, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateLessThan(Byte value) {
            addCriterion("networkState <", value, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateLessThanOrEqualTo(Byte value) {
            addCriterion("networkState <=", value, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateIn(List<Byte> values) {
            addCriterion("networkState in", values, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateNotIn(List<Byte> values) {
            addCriterion("networkState not in", values, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateBetween(Byte value1, Byte value2) {
            addCriterion("networkState between", value1, value2, "networkstate");
            return (Criteria) this;
        }

        public Criteria andNetworkstateNotBetween(Byte value1, Byte value2) {
            addCriterion("networkState not between", value1, value2, "networkstate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andLongitodeIsNull() {
            addCriterion("longitode is null");
            return (Criteria) this;
        }

        public Criteria andLongitodeIsNotNull() {
            addCriterion("longitode is not null");
            return (Criteria) this;
        }

        public Criteria andLongitodeEqualTo(String value) {
            addCriterion("longitode =", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeNotEqualTo(String value) {
            addCriterion("longitode <>", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeGreaterThan(String value) {
            addCriterion("longitode >", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeGreaterThanOrEqualTo(String value) {
            addCriterion("longitode >=", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeLessThan(String value) {
            addCriterion("longitode <", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeLessThanOrEqualTo(String value) {
            addCriterion("longitode <=", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeLike(String value) {
            addCriterion("longitode like", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeNotLike(String value) {
            addCriterion("longitode not like", value, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeIn(List<String> values) {
            addCriterion("longitode in", values, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeNotIn(List<String> values) {
            addCriterion("longitode not in", values, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeBetween(String value1, String value2) {
            addCriterion("longitode between", value1, value2, "longitode");
            return (Criteria) this;
        }

        public Criteria andLongitodeNotBetween(String value1, String value2) {
            addCriterion("longitode not between", value1, value2, "longitode");
            return (Criteria) this;
        }

        public Criteria andDimensionIsNull() {
            addCriterion("dimension is null");
            return (Criteria) this;
        }

        public Criteria andDimensionIsNotNull() {
            addCriterion("dimension is not null");
            return (Criteria) this;
        }

        public Criteria andDimensionEqualTo(String value) {
            addCriterion("dimension =", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotEqualTo(String value) {
            addCriterion("dimension <>", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionGreaterThan(String value) {
            addCriterion("dimension >", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionGreaterThanOrEqualTo(String value) {
            addCriterion("dimension >=", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionLessThan(String value) {
            addCriterion("dimension <", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionLessThanOrEqualTo(String value) {
            addCriterion("dimension <=", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionLike(String value) {
            addCriterion("dimension like", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotLike(String value) {
            addCriterion("dimension not like", value, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionIn(List<String> values) {
            addCriterion("dimension in", values, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotIn(List<String> values) {
            addCriterion("dimension not in", values, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionBetween(String value1, String value2) {
            addCriterion("dimension between", value1, value2, "dimension");
            return (Criteria) this;
        }

        public Criteria andDimensionNotBetween(String value1, String value2) {
            addCriterion("dimension not between", value1, value2, "dimension");
            return (Criteria) this;
        }

        public Criteria andRegisterflagIsNull() {
            addCriterion("registerFlag is null");
            return (Criteria) this;
        }

        public Criteria andRegisterflagIsNotNull() {
            addCriterion("registerFlag is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterflagEqualTo(String value) {
            addCriterion("registerFlag =", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagNotEqualTo(String value) {
            addCriterion("registerFlag <>", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagGreaterThan(String value) {
            addCriterion("registerFlag >", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagGreaterThanOrEqualTo(String value) {
            addCriterion("registerFlag >=", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagLessThan(String value) {
            addCriterion("registerFlag <", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagLessThanOrEqualTo(String value) {
            addCriterion("registerFlag <=", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagLike(String value) {
            addCriterion("registerFlag like", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagNotLike(String value) {
            addCriterion("registerFlag not like", value, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagIn(List<String> values) {
            addCriterion("registerFlag in", values, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagNotIn(List<String> values) {
            addCriterion("registerFlag not in", values, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagBetween(String value1, String value2) {
            addCriterion("registerFlag between", value1, value2, "registerflag");
            return (Criteria) this;
        }

        public Criteria andRegisterflagNotBetween(String value1, String value2) {
            addCriterion("registerFlag not between", value1, value2, "registerflag");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeIsNull() {
            addCriterion("makeOpCode is null");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeIsNotNull() {
            addCriterion("makeOpCode is not null");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeEqualTo(String value) {
            addCriterion("makeOpCode =", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeNotEqualTo(String value) {
            addCriterion("makeOpCode <>", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeGreaterThan(String value) {
            addCriterion("makeOpCode >", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeGreaterThanOrEqualTo(String value) {
            addCriterion("makeOpCode >=", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeLessThan(String value) {
            addCriterion("makeOpCode <", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeLessThanOrEqualTo(String value) {
            addCriterion("makeOpCode <=", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeLike(String value) {
            addCriterion("makeOpCode like", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeNotLike(String value) {
            addCriterion("makeOpCode not like", value, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeIn(List<String> values) {
            addCriterion("makeOpCode in", values, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeNotIn(List<String> values) {
            addCriterion("makeOpCode not in", values, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeBetween(String value1, String value2) {
            addCriterion("makeOpCode between", value1, value2, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakeopcodeNotBetween(String value1, String value2) {
            addCriterion("makeOpCode not between", value1, value2, "makeopcode");
            return (Criteria) this;
        }

        public Criteria andMakedateIsNull() {
            addCriterion("makeDate is null");
            return (Criteria) this;
        }

        public Criteria andMakedateIsNotNull() {
            addCriterion("makeDate is not null");
            return (Criteria) this;
        }

        public Criteria andMakedateEqualTo(Date value) {
            addCriterion("makeDate =", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotEqualTo(Date value) {
            addCriterion("makeDate <>", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateGreaterThan(Date value) {
            addCriterion("makeDate >", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateGreaterThanOrEqualTo(Date value) {
            addCriterion("makeDate >=", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateLessThan(Date value) {
            addCriterion("makeDate <", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateLessThanOrEqualTo(Date value) {
            addCriterion("makeDate <=", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateIn(List<Date> values) {
            addCriterion("makeDate in", values, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotIn(List<Date> values) {
            addCriterion("makeDate not in", values, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateBetween(Date value1, Date value2) {
            addCriterion("makeDate between", value1, value2, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotBetween(Date value1, Date value2) {
            addCriterion("makeDate not between", value1, value2, "makedate");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeIsNull() {
            addCriterion("lastModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeIsNotNull() {
            addCriterion("lastModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeEqualTo(Date value) {
            addCriterion("lastModifyTime =", value, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeNotEqualTo(Date value) {
            addCriterion("lastModifyTime <>", value, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeGreaterThan(Date value) {
            addCriterion("lastModifyTime >", value, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastModifyTime >=", value, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeLessThan(Date value) {
            addCriterion("lastModifyTime <", value, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeLessThanOrEqualTo(Date value) {
            addCriterion("lastModifyTime <=", value, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeIn(List<Date> values) {
            addCriterion("lastModifyTime in", values, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeNotIn(List<Date> values) {
            addCriterion("lastModifyTime not in", values, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeBetween(Date value1, Date value2) {
            addCriterion("lastModifyTime between", value1, value2, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andLastmodifytimeNotBetween(Date value1, Date value2) {
            addCriterion("lastModifyTime not between", value1, value2, "lastmodifytime");
            return (Criteria) this;
        }

        public Criteria andBoxcodeIsNull() {
            addCriterion("boxCode is null");
            return (Criteria) this;
        }

        public Criteria andBoxcodeIsNotNull() {
            addCriterion("boxCode is not null");
            return (Criteria) this;
        }

        public Criteria andBoxcodeEqualTo(String value) {
            addCriterion("boxCode =", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeNotEqualTo(String value) {
            addCriterion("boxCode <>", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeGreaterThan(String value) {
            addCriterion("boxCode >", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeGreaterThanOrEqualTo(String value) {
            addCriterion("boxCode >=", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeLessThan(String value) {
            addCriterion("boxCode <", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeLessThanOrEqualTo(String value) {
            addCriterion("boxCode <=", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeLike(String value) {
            addCriterion("boxCode like", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeNotLike(String value) {
            addCriterion("boxCode not like", value, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeIn(List<String> values) {
            addCriterion("boxCode in", values, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeNotIn(List<String> values) {
            addCriterion("boxCode not in", values, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeBetween(String value1, String value2) {
            addCriterion("boxCode between", value1, value2, "boxcode");
            return (Criteria) this;
        }

        public Criteria andBoxcodeNotBetween(String value1, String value2) {
            addCriterion("boxCode not between", value1, value2, "boxcode");
            return (Criteria) this;
        }

        public Criteria andNumberingIsNull() {
            addCriterion("numbering is null");
            return (Criteria) this;
        }

        public Criteria andNumberingIsNotNull() {
            addCriterion("numbering is not null");
            return (Criteria) this;
        }

        public Criteria andNumberingEqualTo(Integer value) {
            addCriterion("numbering =", value, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingNotEqualTo(Integer value) {
            addCriterion("numbering <>", value, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingGreaterThan(Integer value) {
            addCriterion("numbering >", value, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingGreaterThanOrEqualTo(Integer value) {
            addCriterion("numbering >=", value, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingLessThan(Integer value) {
            addCriterion("numbering <", value, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingLessThanOrEqualTo(Integer value) {
            addCriterion("numbering <=", value, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingIn(List<Integer> values) {
            addCriterion("numbering in", values, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingNotIn(List<Integer> values) {
            addCriterion("numbering not in", values, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingBetween(Integer value1, Integer value2) {
            addCriterion("numbering between", value1, value2, "numbering");
            return (Criteria) this;
        }

        public Criteria andNumberingNotBetween(Integer value1, Integer value2) {
            addCriterion("numbering not between", value1, value2, "numbering");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andDumpenergyIsNull() {
            addCriterion("dumpEnergy is null");
            return (Criteria) this;
        }

        public Criteria andDumpenergyIsNotNull() {
            addCriterion("dumpEnergy is not null");
            return (Criteria) this;
        }

        public Criteria andDumpenergyEqualTo(String value) {
            addCriterion("dumpEnergy =", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyNotEqualTo(String value) {
            addCriterion("dumpEnergy <>", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyGreaterThan(String value) {
            addCriterion("dumpEnergy >", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyGreaterThanOrEqualTo(String value) {
            addCriterion("dumpEnergy >=", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyLessThan(String value) {
            addCriterion("dumpEnergy <", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyLessThanOrEqualTo(String value) {
            addCriterion("dumpEnergy <=", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyLike(String value) {
            addCriterion("dumpEnergy like", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyNotLike(String value) {
            addCriterion("dumpEnergy not like", value, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyIn(List<String> values) {
            addCriterion("dumpEnergy in", values, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyNotIn(List<String> values) {
            addCriterion("dumpEnergy not in", values, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyBetween(String value1, String value2) {
            addCriterion("dumpEnergy between", value1, value2, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andDumpenergyNotBetween(String value1, String value2) {
            addCriterion("dumpEnergy not between", value1, value2, "dumpenergy");
            return (Criteria) this;
        }

        public Criteria andAppkeyIsNull() {
            addCriterion("appKey is null");
            return (Criteria) this;
        }

        public Criteria andAppkeyIsNotNull() {
            addCriterion("appKey is not null");
            return (Criteria) this;
        }

        public Criteria andAppkeyEqualTo(String value) {
            addCriterion("appKey =", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotEqualTo(String value) {
            addCriterion("appKey <>", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyGreaterThan(String value) {
            addCriterion("appKey >", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyGreaterThanOrEqualTo(String value) {
            addCriterion("appKey >=", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyLessThan(String value) {
            addCriterion("appKey <", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyLessThanOrEqualTo(String value) {
            addCriterion("appKey <=", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyLike(String value) {
            addCriterion("appKey like", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotLike(String value) {
            addCriterion("appKey not like", value, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyIn(List<String> values) {
            addCriterion("appKey in", values, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotIn(List<String> values) {
            addCriterion("appKey not in", values, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyBetween(String value1, String value2) {
            addCriterion("appKey between", value1, value2, "appkey");
            return (Criteria) this;
        }

        public Criteria andAppkeyNotBetween(String value1, String value2) {
            addCriterion("appKey not between", value1, value2, "appkey");
            return (Criteria) this;
        }

        public Criteria andRfidIsNull() {
            addCriterion("rfid is null");
            return (Criteria) this;
        }

        public Criteria andRfidIsNotNull() {
            addCriterion("rfid is not null");
            return (Criteria) this;
        }

        public Criteria andRfidEqualTo(String value) {
            addCriterion("rfid =", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidNotEqualTo(String value) {
            addCriterion("rfid <>", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidGreaterThan(String value) {
            addCriterion("rfid >", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidGreaterThanOrEqualTo(String value) {
            addCriterion("rfid >=", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidLessThan(String value) {
            addCriterion("rfid <", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidLessThanOrEqualTo(String value) {
            addCriterion("rfid <=", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidLike(String value) {
            addCriterion("rfid like", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidNotLike(String value) {
            addCriterion("rfid not like", value, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidIn(List<String> values) {
            addCriterion("rfid in", values, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidNotIn(List<String> values) {
            addCriterion("rfid not in", values, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidBetween(String value1, String value2) {
            addCriterion("rfid between", value1, value2, "rfid");
            return (Criteria) this;
        }

        public Criteria andRfidNotBetween(String value1, String value2) {
            addCriterion("rfid not between", value1, value2, "rfid");
            return (Criteria) this;
        }

        public Criteria andGuistatusIsNull() {
            addCriterion("guistatus is null");
            return (Criteria) this;
        }

        public Criteria andGuistatusIsNotNull() {
            addCriterion("guistatus is not null");
            return (Criteria) this;
        }

        public Criteria andGuistatusEqualTo(Integer value) {
            addCriterion("guistatus =", value, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusNotEqualTo(Integer value) {
            addCriterion("guistatus <>", value, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusGreaterThan(Integer value) {
            addCriterion("guistatus >", value, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("guistatus >=", value, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusLessThan(Integer value) {
            addCriterion("guistatus <", value, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusLessThanOrEqualTo(Integer value) {
            addCriterion("guistatus <=", value, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusIn(List<Integer> values) {
            addCriterion("guistatus in", values, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusNotIn(List<Integer> values) {
            addCriterion("guistatus not in", values, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusBetween(Integer value1, Integer value2) {
            addCriterion("guistatus between", value1, value2, "guistatus");
            return (Criteria) this;
        }

        public Criteria andGuistatusNotBetween(Integer value1, Integer value2) {
            addCriterion("guistatus not between", value1, value2, "guistatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table terminal
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table terminal
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}