package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

import java.util.ArrayList;
import java.util.List;

public class UserAndRuntimeBoundEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public UserAndRuntimeBoundEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsercardidIsNull() {
            addCriterion("userCardID is null");
            return (Criteria) this;
        }

        public Criteria andUsercardidIsNotNull() {
            addCriterion("userCardID is not null");
            return (Criteria) this;
        }

        public Criteria andUsercardidEqualTo(String value) {
            addCriterion("userCardID =", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidNotEqualTo(String value) {
            addCriterion("userCardID <>", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidGreaterThan(String value) {
            addCriterion("userCardID >", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidGreaterThanOrEqualTo(String value) {
            addCriterion("userCardID >=", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidLessThan(String value) {
            addCriterion("userCardID <", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidLessThanOrEqualTo(String value) {
            addCriterion("userCardID <=", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidLike(String value) {
            addCriterion("userCardID like", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidNotLike(String value) {
            addCriterion("userCardID not like", value, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidIn(List<String> values) {
            addCriterion("userCardID in", values, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidNotIn(List<String> values) {
            addCriterion("userCardID not in", values, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidBetween(String value1, String value2) {
            addCriterion("userCardID between", value1, value2, "usercardid");
            return (Criteria) this;
        }

        public Criteria andUsercardidNotBetween(String value1, String value2) {
            addCriterion("userCardID not between", value1, value2, "usercardid");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeIsNull() {
            addCriterion("runTimeCode is null");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeIsNotNull() {
            addCriterion("runTimeCode is not null");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeEqualTo(Integer value) {
            addCriterion("runTimeCode =", value, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeNotEqualTo(Integer value) {
            addCriterion("runTimeCode <>", value, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeGreaterThan(Integer value) {
            addCriterion("runTimeCode >", value, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("runTimeCode >=", value, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeLessThan(Integer value) {
            addCriterion("runTimeCode <", value, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeLessThanOrEqualTo(Integer value) {
            addCriterion("runTimeCode <=", value, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeIn(List<Integer> values) {
            addCriterion("runTimeCode in", values, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeNotIn(List<Integer> values) {
            addCriterion("runTimeCode not in", values, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeBetween(Integer value1, Integer value2) {
            addCriterion("runTimeCode between", value1, value2, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andRuntimecodeNotBetween(Integer value1, Integer value2) {
            addCriterion("runTimeCode not between", value1, value2, "runtimecode");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userandruntimebound
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userandruntimebound
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}