package com.hzdongcheng.softwareplatform.intelligentstorage.dal.dao.table.entity;

public class WxmenuEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmenu.codes
     *
     * @mbg.generated
     */
    private String codes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmenu.pcodes
     *
     * @mbg.generated
     */
    private String pcodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmenu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmenu.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmenu.areaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxmenu.contentes
     *
     * @mbg.generated
     */
    private String contentes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmenu.codes
     *
     * @return the value of wxmenu.codes
     *
     * @mbg.generated
     */
    public String getCodes() {
        return codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmenu.codes
     *
     * @param codes the value for wxmenu.codes
     *
     * @mbg.generated
     */
    public void setCodes(String codes) {
        this.codes = codes == null ? null : codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmenu.pcodes
     *
     * @return the value of wxmenu.pcodes
     *
     * @mbg.generated
     */
    public String getPcodes() {
        return pcodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmenu.pcodes
     *
     * @param pcodes the value for wxmenu.pcodes
     *
     * @mbg.generated
     */
    public void setPcodes(String pcodes) {
        this.pcodes = pcodes == null ? null : pcodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmenu.name
     *
     * @return the value of wxmenu.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmenu.name
     *
     * @param name the value for wxmenu.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmenu.company
     *
     * @return the value of wxmenu.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmenu.company
     *
     * @param company the value for wxmenu.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmenu.areaCode
     *
     * @return the value of wxmenu.areaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmenu.areaCode
     *
     * @param areacode the value for wxmenu.areaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxmenu.contentes
     *
     * @return the value of wxmenu.contentes
     *
     * @mbg.generated
     */
    public String getContentes() {
        return contentes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxmenu.contentes
     *
     * @param contentes the value for wxmenu.contentes
     *
     * @mbg.generated
     */
    public void setContentes(String contentes) {
        this.contentes = contentes == null ? null : contentes.trim();
    }
}